name = "leanaide"
defaultTargets = ["LeanAide", "LeanCodePrompts", "translate", "leanaide_process"]
testDriver = "LeanAideTest"

[[require]]
name= "leanaidecore"
path ="./LeanAideCore"

[[require]]
name = "Hammer"
git = "https://github.com/JOSHCLUNE/LeanHammer"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "LeanAide"

[[lean_lib]]
name = "LeanCodePrompts"

[[lean_lib]]
name = "DataGenAide"

[[lean_lib]]
name = "LeanAideTest"

[[lean_exe]]
name = "datagen"
supportInterpreter = true

[[lean_exe]]
name = "elabdatagen"
supportInterpreter = true

[[lean_exe]]
name = "bulkelab"
supportInterpreter = true

[[lean_exe]]
name = "translate"
supportInterpreter = true

[[lean_exe]]
name = "leanaide_process"
supportInterpreter = true

[[lean_exe]]
name = "promptsgen"
supportInterpreter = true

[[lean_exe]]
name = "thmextract"
supportInterpreter = true

[[lean_exe]]
name = "bulkchk"
supportInterpreter = true

[[lean_exe]]
name = "batchcheck"
supportInterpreter = true

[[lean_exe]]
name = "getpremises"
supportInterpreter = true

[[lean_exe]]
name = "getidents"
supportInterpreter = true

[[lean_exe]]
name = "props"
supportInterpreter = true

[[lean_exe]]
name = "dedup"

[[lean_exe]]
name = "getdefns"
supportInterpreter = true

[[lean_exe]]
name = "chkthms"
supportInterpreter = true

[[lean_exe]]
name = "writedocs"
supportInterpreter = true

[[lean_exe]]
name = "writedescs"
supportInterpreter = true

[[lean_exe]]
name = "writedescs_docs"
supportInterpreter = true

[[lean_exe]]
name = "rewritedescs"
supportInterpreter = true

[[lean_exe]]
name = "updatedescs"
supportInterpreter = true

[[lean_exe]]
name = "descweb"
supportInterpreter = true

[[lean_exe]]
name = "check_descs"
supportInterpreter = true

[[lean_exe]]
name = "descdetails"
supportInterpreter = true

[[lean_exe]]
name = "putnamelab"
supportInterpreter = true

[[lean_exe]]
name = "check_command"
supportInterpreter = true
