name = "leanaideclient"
defaultTargets = ["ClientTest"]

[[require]]
name= "leanaidecore"
path ="../LeanAideCore"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0"

[[lean_lib]]
name = "ClientTest"
